# Scratchwork 7 - Units of a Ring (and Monoid)

Units appear to be usually defined in the context of the multiplicative operation of a Ring, but the only requirement for an algebra to have units is that it have an identity element.  So, here, a ``units`` method has been defined for the Monoid class.  A Ring doesn't have to have a multiplicative identity, but if it does, then its multiplicative part is a Monoid.  The Ring's units can then be derived by extracting the multiplicative part of the Ring, and then applying the ``units`` method to the extracted Monoid.

In [1]:
from finite_algebras import *
from cayley_table import *
from permutations import *

In [2]:
import os
aa_path = os.path.join(os.getenv("PYPROJ"), "abstract_algebra")
alg_dir = os.path.join(aa_path, "Algebras")

In [3]:
ex = Examples(alg_dir)

======================================================================
                           Example Algebras
----------------------------------------------------------------------
  16 example algebras are available.
  Use "Examples[INDEX]" to retrieve a specific example,
  where INDEX is the first number on each line below:
----------------------------------------------------------------------
0: A4 -- Alternating group on 4 letters (AKA Tetrahedral group)
1: D3 -- https://en.wikipedia.org/wiki/Dihedral_group_of_order_6
2: D4 -- Dihedral group on four vertices
3: Pinter29 -- Non-abelian group, p.29, 'A Book of Abstract Algebra' by Charles C. Pinter
4: RPS -- Rock, Paper, Scissors Magma
5: S3 -- Symmetric group on 3 letters
6: S3X -- Another version of the symmetric group on 3 letters
7: V4 -- Klein-4 group
8: Z4 -- Cyclic group of order 4
9: F4 -- Field with 4 elements (from Wikipedia)
10: mag_id -- Magma with Identity
11: Example 1.4.1 -- See: Groupoids and Smarandache Groupoids by W. B. Vasantha Kandasamy
12: Ex6 -- Example 6: http://www-groups.mcs.st-andrews.ac.uk/~john/MT4517/Lectures/L3.html
13: Q8 -- Quaternion Group
14: SD16 -- Semidihedral group of order 16
15: A5 -- Alternating group on 5 letters
======================================================================

## Create an example Ring

In [4]:
help(generate_algebra_mod_n)

Help on function generate_algebra_mod_n in module finite_algebras:

generate_algebra_mod_n(n, elem_name='a', name=None, description=None)
    Generate a Ring (or Field) based on integer addition and multiplication modulo n.
    If n is prime, then result will be a Field, otherwise it will be a Ring.

In [5]:
Zmod12 = generate_algebra_mod_n(12)
Zmod12.about()

** Ring **
Name: R12
Instance ID: 140651062966736
Description: Autogenerated Ring of integers mod 12
Order: 12
Identity: a0
Associative? Yes
Commutative? Yes
Cyclic?: Yes
  Generators: ['a1', 'a11', 'a5', 'a7']
Elements:
   Index   Name   Inverse  Order
      0      a0      a0       1
      1      a1     a11      12
      2      a2     a10       6
      3      a3      a9       4
      4      a4      a8       3
      5      a5      a7      12
      6      a6      a6       2
      7      a7      a5      12
      8      a8      a4       3
      9      a9      a3       4
     10     a10      a2       6
     11     a11      a1      12
Cayley Table (showing indices):
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2],
 [4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3],
 [5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4],
 [6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5],
 [7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6],
 [8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7],
 [9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8],
 [10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
Mult. Identity: a1
Mult. Commutative? Yes
Zero Divisors: ['a2', 'a3', 'a4', 'a6', 'a8', 'a9', 'a10']
Multiplicative Cayley Table (showing indices):
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 2, 4, 6, 8, 10, 0, 2, 4, 6, 8, 10],
 [0, 3, 6, 9, 0, 3, 6, 9, 0, 3, 6, 9],
 [0, 4, 8, 0, 4, 8, 0, 4, 8, 0, 4, 8],
 [0, 5, 10, 3, 8, 1, 6, 11, 4, 9, 2, 7],
 [0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6],
 [0, 7, 2, 9, 4, 11, 6, 1, 8, 3, 10, 5],
 [0, 8, 4, 0, 8, 4, 0, 8, 4, 0, 8, 4],
 [0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3],
 [0, 10, 8, 6, 4, 2, 0, 10, 8, 6, 4, 2],
 [0, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]]

### Extract Multiplicative Part of the Ring (it's a Monoid here)

In [6]:
mon = Zmod12.extract_multiplicative_algebra()
mon.about()

** Monoid **
Name: R12.Mult
Instance ID: 140651063111056
Description: Multiplicative-only portion of R12
Order: 12
Identity: a1
Associative? Yes
Commutative? Yes
Cyclic?: No
Elements: ['a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11']
Has Inverses? No
Cayley Table (showing indices):
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 2, 4, 6, 8, 10, 0, 2, 4, 6, 8, 10],
 [0, 3, 6, 9, 0, 3, 6, 9, 0, 3, 6, 9],
 [0, 4, 8, 0, 4, 8, 0, 4, 8, 0, 4, 8],
 [0, 5, 10, 3, 8, 1, 6, 11, 4, 9, 2, 7],
 [0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6],
 [0, 7, 2, 9, 4, 11, 6, 1, 8, 3, 10, 5],
 [0, 8, 4, 0, 8, 4, 0, 8, 4, 0, 8, 4],
 [0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3],
 [0, 10, 8, 6, 4, 2, 0, 10, 8, 6, 4, 2],
 [0, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]]

### Get Units

**Units of a Monoid**

In [7]:
mon.units()  # Monoid Units

['a1', 'a5', 'a7', 'a11']

Return the indices of the unit elements as follows:

In [8]:
mon.units(return_names=False)

[1, 5, 7, 11]

**Units of a Ring**

In [9]:
Zmod12.units()  # Ring Units (names)

['a1', 'a5', 'a7', 'a11']

In [10]:
Zmod12.units(return_names=False)  # Ring Units (indices)

[1, 5, 7, 11]

**Units of a Group**

Just doing this a check.  The units of a Group are **all** of its elements, as shown below:

In [11]:
grp = ex[0]
print(f"{grp.name}: {grp.description}")
print(f"Order: {grp.order}")
print(f"Units: {grp.units(return_names=False)}")

A4: Alternating group on 4 letters (AKA Tetrahedral group)
Order: 12
Units: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### Units Subgroup

In [12]:
mon.closure(mon.units(), include_inverses=False)

['a11', 'a5', 'a1', 'a7']

In [13]:
mon_units_subgrp = mon.subalgebra_from_elements(mon.units(),
                                                name=f"{mon.name}_UNITS",
                                                desc=f"Unit subgroup of {mon.name}")
mon_units_subgrp.about()

** Group **
Name: R12.Mult_UNITS
Instance ID: 140649845392848
Description: Unit subgroup of R12.Mult
Order: 4
Identity: a1
Associative? Yes
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0      a1      a1       1
      1      a5      a5       2
      2      a7      a7       2
      3     a11     a11       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [14]:
mon.units_subgroup()

Group(
'R12.Mult_Units',
'Unit subgroup of Monoid: R12.Mult',
['a1', 'a5', 'a7', 'a11'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
)

In [15]:
Zmod12.units_subgroup()

Group(
'R12_Units',
'Unit subgroup of Ring: R12',
['a1', 'a5', 'a7', 'a11'],
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
)

In [16]:
grp.units_subgroup()

Group(
'A4_Units',
'Unit subgroup of Group: A4',
['()', '(1 3 2)', '(1 2 3)', '(0 1)(2 3)', '(0 1 2)', '(0 1 3)', '(0 3 1)', '(0 3 2)', '(0 3)(1 2)', '(0 2 3)', '(0 2 1)', '(0 2)(1 3)'],
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [1, 2, 0, 6, 7, 8, 10, 11, 9, 5, 3, 4], [2, 0, 1, 10, 11, 9, 3, 4, 5, 8, 6, 7], [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8], [4, 5, 3, 9, 10, 11, 7, 8, 6, 2, 0, 1], [5, 3, 4, 7, 8, 6, 0, 1, 2, 11, 9, 10], [6, 7, 8, 1, 2, 0, 5, 3, 4, 10, 11, 9], [7, 8, 6, 5, 3, 4, 11, 9, 10, 0, 1, 2], [8, 6, 7, 11, 9, 10, 1, 2, 0, 4, 5, 3], [9, 10, 11, 4, 5, 3, 2, 0, 1, 7, 8, 6], [10, 11, 9, 2, 0, 1, 8, 6, 7, 3, 4, 5], [11, 9, 10, 8, 6, 7, 4, 5, 3, 1, 2, 0]]
)