# Generating Groups based on Relative Primes < n

## Summary

Generate and examine the "relative primes" Groups based on the values, 5, 8, 10, 12:
* Each one has order 4
* All four are abelian (commutative)
* g5 & g10 are cyclic and isomorphic to each other
* g8 & g12 are not cyclic and isomorphic to each other

Compare the Groups, above, to the 4th-order algebras contained in the examples: v4, z4, f4, ex6:
* z4, the cyclic group of order 4, is isomorphic to g5 & g10
* v4, the Klein-4 group, is isomorphic to g8 & g12

f4 is a Field and ex6 is a Ring:
* The additive portions (Group) of both f4 & ex6 are isomorphic to g8 & g12
* The multiplicative portion of f4 is a Monoid, but the abelian subgroup of it is isomorphic to the cyclic Group of order 3 (ie., $Z_3$)

In [1]:
from finite_algebras import *

In [2]:
import os
aa_path = os.path.join(os.getenv("PYPROJ"), "abstract_algebra")
alg_dir = os.path.join(aa_path, "Algebras")

Find all n such that there are 4 relative primes less than n
(i.e., totient(n) == 4)

In [3]:
for i in range(20):
    relp = relative_primes(i)
    if len(relp) == 4:
        print(f"{i} : {relp}")

5 : [1, 2, 3, 4]
8 : [1, 3, 5, 7]
10 : [1, 3, 7, 9]
12 : [1, 5, 7, 11]

In [4]:
g5 = generate_relative_primes_group(5)
g8 = generate_relative_primes_group(8)
g10 = generate_relative_primes_group(10)
g12 = generate_relative_primes_group(12)

In [5]:
g5.about()

** Group **
Name: RelPrimes<5
Instance ID: 140459955386832
Description: Autogenerated group based on relative primes < 5
Order: 4
Identity: 1
Commutative? Yes
Cyclic?: Yes
  Generators: [2, 3]
Elements:
   Index   Name   Inverse  Order
      0       1       1       1
      1       2       3       4
      2       3       2       4
      3       4       4       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]

In [6]:
g8.about()

** Group **
Name: RelPrimes<8
Instance ID: 140459955538896
Description: Autogenerated group based on relative primes < 8
Order: 4
Identity: 1
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       1       1       1
      1       3       3       2
      2       5       5       2
      3       7       7       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [7]:
g10.about()

** Group **
Name: RelPrimes<10
Instance ID: 140459955539152
Description: Autogenerated group based on relative primes < 10
Order: 4
Identity: 1
Commutative? Yes
Cyclic?: Yes
  Generators: [3, 7]
Elements:
   Index   Name   Inverse  Order
      0       1       1       1
      1       3       7       4
      2       7       3       4
      3       9       9       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 3, 0, 2], [2, 0, 3, 1], [3, 2, 1, 0]]

In [8]:
g12.about()

** Group **
Name: RelPrimes<12
Instance ID: 140459955539408
Description: Autogenerated group based on relative primes < 12
Order: 4
Identity: 1
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       1       1       1
      1       5       5       2
      2       7       7       2
      3      11      11       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [9]:
g5.isomorphic(g10)

{1: 1, 2: 3, 3: 7, 4: 9}

In [10]:
g8.isomorphic(g12)

{1: 1, 3: 5, 5: 7, 7: 11}

In [11]:
ex = Examples(alg_dir)

======================================================================
                           Example Algebras
----------------------------------------------------------------------
  16 example algebras are available.
  Use "Examples[INDEX]" to retrieve a specific example,
  where INDEX is the first number on each line below:
----------------------------------------------------------------------
0: A4 -- Alternating group on 4 letters (AKA Tetrahedral group)
1: D3 -- https://en.wikipedia.org/wiki/Dihedral_group_of_order_6
2: D4 -- Dihedral group on four vertices
3: Pinter29 -- Non-abelian group, p.29, 'A Book of Abstract Algebra' by Charles C. Pinter
4: RPS -- Rock, Paper, Scissors Magma
5: S3 -- Symmetric group on 3 letters
6: S3X -- Another version of the symmetric group on 3 letters
7: V4 -- Klein-4 group
8: Z4 -- Cyclic group of order 4
9: F4 -- Field with 4 elements (from Wikipedia)
10: mag_id -- Magma with Identity
11: Example 1.4.1 -- See: Groupoids and Smarandache Groupoids by W. B. Vasantha Kandasamy
12: Ex6 -- Example 6: http://www-groups.mcs.st-andrews.ac.uk/~john/MT4517/Lectures/L3.html
13: Q8 -- Quaternion Group
14: SD16 -- Semidihedral group of order 16
15: A5 -- Alternating group on 5 letters
======================================================================

In [12]:
for i in range(16):
    order = ex[i].order
    if order == 4:
        print(f"{i} : {ex[i].order} : {ex[i].name} : {type(ex[i])}")

7 : 4 : V4 : <class 'finite_algebras.Group'>
8 : 4 : Z4 : <class 'finite_algebras.Group'>
9 : 4 : F4 : <class 'finite_algebras.Field'>
12 : 4 : Ex6 : <class 'finite_algebras.Ring'>

In [13]:
v4 = ex[7]
z4 = ex[8]
f4 = ex[9]
ex6 = ex[12]

In [14]:
v4.about()

** Group **
Name: V4
Instance ID: 140459955537872
Description: Klein-4 group
Order: 4
Identity: e
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       h       h       2
      2       v       v       2
      3       r       r       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [15]:
v4.isomorphic(g8)

{'e': 1, 'h': 3, 'v': 5, 'r': 7}

In [16]:
z4.about()

** Group **
Name: Z4
Instance ID: 140459122251664
Description: Cyclic group of order 4
Order: 4
Identity: e
Commutative? Yes
Cyclic?: Yes
  Generators: ['a', 'a^3']
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       a     a^3       4
      2     a^2     a^2       2
      3     a^3       a       4
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 2, 3, 0], [2, 3, 0, 1], [3, 0, 1, 2]]

In [17]:
z4.isomorphic(g5)

{'e': 1, 'a': 2, 'a^2': 4, 'a^3': 3}

In [18]:
f4.about()

** Field **
Name: F4
Instance ID: 140459122251344
Description: Field with 4 elements (from Wikipedia)
Order: 4
Identity: 0
Commutative? Yes
Cyclic?: Yes
  Generators: ['1+a', 'a']
Elements:
   Index   Name   Inverse  Order
      0       0       0       1
      1       1       1       2
      2       a       a       2
      3     1+a     1+a       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]
Mult. Identity: 1
Mult. Commutative? Yes
Zero Divisors: None
Multiplicative Cayley Table (showing indices):
[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 3, 1], [0, 3, 1, 2]]

In [19]:
f4_add = f4.extract_additive_algebra()
f4_add.about()

** Group **
Name: F4.Add
Instance ID: 140459122316624
Description: Additive-only portion of F4
Order: 4
Identity: 0
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       0       0       1
      1       1       1       2
      2       a       a       2
      3     1+a     1+a       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [20]:
f4_add.isomorphic(g8)

{'0': 1, '1': 3, 'a': 5, '1+a': 7}

In [21]:
f4_mult = f4.extract_multiplicative_algebra()
f4_mult.about()

** Monoid **
Name: F4.Mult
Instance ID: 140459122276048
Description: Multiplicative-only portion of F4
Order: 4
Identity: 1
Associative? Yes
Commutative? Yes
Cyclic?: No
Elements: ['0', '1', 'a', '1+a']
Has Inverses? No
Cayley Table (showing indices):
[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 3, 1], [0, 3, 1, 2]]

In [22]:
f4_mult_grp = f4.mult_abelian_subgroup()
f4_mult_grp.about()

** Group **
Name: F4_G
Instance ID: 140459122251856
Description: Multiplicative abelian Group of F4
Order: 3
Identity: 1
Commutative? Yes
Cyclic?: Yes
  Generators: ['1+a', 'a']
Elements:
   Index   Name   Inverse  Order
      0       1       1       1
      1       a     1+a       3
      2     1+a       a       3
Cayley Table (showing indices):
[[0, 1, 2], [1, 2, 0], [2, 0, 1]]

In [23]:
z3 = generate_cyclic_group(3)
z3.about()

** Group **
Name: Z3
Instance ID: 140459122353744
Description: Autogenerated cyclic Group of order 3
Order: 3
Identity: e
Commutative? Yes
Cyclic?: Yes
  Generators: ['a', 'a^2']
Elements:
   Index   Name   Inverse  Order
      0       e       e       1
      1       a     a^2       3
      2     a^2       a       3
Cayley Table (showing indices):
[[0, 1, 2], [1, 2, 0], [2, 0, 1]]

In [24]:
f4_mult_grp.isomorphic(z3)

{'1': 'e', 'a': 'a', '1+a': 'a^2'}

In [25]:
ex6_add = ex6.extract_additive_algebra()
ex6_add.about()

** Group **
Name: Ex6.Add
Instance ID: 140458317125968
Description: Additive-only portion of Ex6
Order: 4
Identity: 0
Commutative? Yes
Cyclic?: No
Elements:
   Index   Name   Inverse  Order
      0       0       0       1
      1       a       a       2
      2       b       b       2
      3       c       c       2
Cayley Table (showing indices):
[[0, 1, 2, 3], [1, 0, 3, 2], [2, 3, 0, 1], [3, 2, 1, 0]]

In [26]:
ex6_add.isomorphic(g8)

{'0': 1, 'a': 3, 'b': 5, 'c': 7}

In [27]:
ex6_mult = ex6.extract_multiplicative_algebra()
ex6_mult.about()

** Semigroup **
Name: Ex6.Mult
Instance ID: 140458317150736
Description: Multiplicative-only portion of Ex6
Order: 4
Identity: None
Associative? Yes
Commutative? No
Cyclic?: No
Elements: ['0', 'a', 'b', 'c']
Has Inverses? No
Cayley Table (showing indices):
[[0, 0, 0, 0], [0, 0, 1, 1], [0, 0, 2, 2], [0, 0, 3, 3]]

In [28]:
ex6_mult.proper_subalgebras()

[Semigroup(
 'Ex6.Mult_subalgebra_0',
 'Subalgebra of: Multiplicative-only portion of Ex6',
 ['0', 'a', 'c'],
 [[0, 0, 0], [0, 0, 1], [0, 0, 2]]
 ),
 Monoid(
 'Ex6.Mult_subalgebra_1',
 'Subalgebra of: Multiplicative-only portion of Ex6',
 ['0', 'b'],
 [[0, 0], [0, 1]]
 ),
 Semigroup(
 'Ex6.Mult_subalgebra_2',
 'Subalgebra of: Multiplicative-only portion of Ex6',
 ['0', 'a'],
 [[0, 0], [0, 0]]
 ),
 Semigroup(
 'Ex6.Mult_subalgebra_3',
 'Subalgebra of: Multiplicative-only portion of Ex6',
 ['b', 'c'],
 [[0, 0], [1, 1]]
 ),
 Monoid(
 'Ex6.Mult_subalgebra_4',
 'Subalgebra of: Multiplicative-only portion of Ex6',
 ['0', 'c'],
 [[0, 0], [0, 1]]
 ),
 Semigroup(
 'Ex6.Mult_subalgebra_5',
 'Subalgebra of: Multiplicative-only portion of Ex6',
 ['0', 'a', 'b'],
 [[0, 0, 0], [0, 0, 1], [0, 0, 2]]
 )]